initial demo env for suction gripper
r-pad/pybullet_envs pull request #3
Opened 2023-12-05 15:52 UTC by ey-cai

Initial PM suction gripper environment for demos (no Gym support)

2023-12-05 23:41 UTC, beneisner commented
Can you write a simple test which exercises this environment? Currently there's no way for me to easily check what's going on.

2023-12-06 00:23 UTC, beneisner requested changes

2023-12-06 00:23 UTC, beneisner commented on src/rpad/pybullet_envs/pm_suction.py
> +# COPIED FROM FLOWBOT, DON'T WANT TO ADD FLOWBOT AS A DEPENDENCY...
separate this out into a second file, flowbot_utils.py, which has a comment in it that it came from there.

2023-12-06 00:23 UTC, beneisner commented on src/rpad/pybullet_envs/pm_suction.py
> +    def __init__(self, obj_id, pm_dataset_path, gripper_path, gui):
Basically, you should create your own version of PMSuctionEnv, which includes similar functions as the original PMSuctionEnv. It should have a PMRenderEnv and a FlyingSuctionGripper, which you should also implement.

The FlyingSuctionGripper should be placed in a different file, probably the FlyingSuctionGripper file from above. It should basically implement the same functions as the original FlyingSuctionGripper, but with the alternative modeling that you've created. All the logic on setting the gripper position, detecting contact, etc. should be encapsulated in that class.

2023-12-06 00:23 UTC, beneisner commented
Let's schedule some time tomorrow to do some pair programming? I think we can bang the rest of this out pretty quick.

2023-12-09 23:22 UTC, ey-cai commented on src/rpad/pybullet_envs/suction_gripper_v2.py
> +        def move_fn() -> Tuple[npt.NDArray, bool]:
This and pull_fn are trivially implemented right now to just copy the original functionality from the demo env - technically set_pull_cmd isn't even applying motor control

2023-12-19 18:07 UTC, beneisner commented on src/rpad/pybullet_envs/pm_suction.py
> +        self.renderer = PybulletRenderer()
this you shouldn't use! caution. basically because it creates its own internal pybullet simulation, ignoring yours. Only use PMRenderEnv

2023-12-19 18:28 UTC, merged